name: Release to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Build the package
        run: poetry build

      - name: Publish to PyPI
        run: poetry publish


